apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-ionkube.fullname" . }}-wordpress
  labels:
    {{- include "wordpress-ionkube.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wordpress