{{- if .Values.persistence.mariadb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-ionkube.fullname" . }}-mariadb-pvc
  labels:
    {{- include "wordpress-ionkube.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.mariadb.size }}
{{- end }}