apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-ionkube.fullname" . }}-mariadb
  labels:
    {{- include "wordpress-ionkube.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.mariadb.rootPassword | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.dbPassword | b64enc | quote }}