apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-ionkube.fullname" . }}-mariadb
  labels:
    {{- include "wordpress-ionkube.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mariadb